{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ksoup-io/0.2.6/ksoup-io-0.2.6.module",
    "group": "com.fleeksoft.ksoup",
    "module": "ksoup-io",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "com.fleeksoft.io",
          "module": "io",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "ksoup-io-wasm-wasi-0.2.6.klib",
          "url": "ksoup-io-wasm-wasi-0.2.6.klib",
          "size": 51097,
          "sha512": "5ef373ba32bbb893ca66836987e59bb9e76c7d3f4fa554c40201be0e38c14c3021a8b349b93bf4974741d50fab5c1746968ac769e096bcc49782ccff7efdee9a",
          "sha256": "71f7791c1bf2ed0735f6e15ba31e73c9f8baee9fc7edb8f6ff39befa60f407e5",
          "sha1": "a60fe33ef73f3f2efad51fba6c0aa2156b38b30e",
          "md5": "2a2976cf7916c43d4d7784d02ace8b6c"
        }
      ]
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "dependencies": [
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "com.fleeksoft.io",
          "module": "io",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "ksoup-io-wasm-wasi-0.2.6.klib",
          "url": "ksoup-io-wasm-wasi-0.2.6.klib",
          "size": 51097,
          "sha512": "5ef373ba32bbb893ca66836987e59bb9e76c7d3f4fa554c40201be0e38c14c3021a8b349b93bf4974741d50fab5c1746968ac769e096bcc49782ccff7efdee9a",
          "sha256": "71f7791c1bf2ed0735f6e15ba31e73c9f8baee9fc7edb8f6ff39befa60f407e5",
          "sha1": "a60fe33ef73f3f2efad51fba6c0aa2156b38b30e",
          "md5": "2a2976cf7916c43d4d7784d02ace8b6c"
        }
      ]
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "files": [
        {
          "name": "ksoup-io-wasm-wasi-0.2.6-sources.jar",
          "url": "ksoup-io-wasm-wasi-0.2.6-sources.jar",
          "size": 11962,
          "sha512": "25849ff0384a3e4bee8332bb7acb758ded1ecd6ba11cb2797235077120471da1f39b114eeae7545a78a66e79cf58f4e1e124c389fd928f3a8ee0c9f98ed80933",
          "sha256": "9fb454471e38d70d5357fc893d146d86e72cb39faa9155f746a884fb4cc8b5dd",
          "sha1": "6515ed95e1344224ce310843c5a441d8c978ba8f",
          "md5": "ca3683cc123b7037d48b7e256b73c71e"
        }
      ]
    }
  ]
}
